### ISSUE TITLE
Hi :wave: and Thx

### ISSUE THREAD

**Issue by markus1189** [TomaSajt/dyalog-nixos-legacy#1]
Hi @TomaSajt,

found no other way to get in contact, but I appreciate your work on markus1189/dyalog-nixos

So I wanted to say thanks!

Best,
Markus

**Comment by TomaSajt** [comment]
Hey @markus1189,

glad I could help! It was fun working on the repo and I also gained a lot of experience with Nix.
I added my discord contacts to my profile if you wanted to contact me outside of GitHub

(also, I'm probably gonna delete this repo sometime in the future, as this was made before I thought of contributing to yours instead)
